import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

function formatInline(text: string): string {
  return text
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code style="background:#f1f5f9; padding:2px 4px; border-radius:4px; font-family:monospace;">$1</code>');
}

function parseMarkdownToSimpleHTML(md: string): string {
  const lines = md.split('\n');
  let inTable = false;
  let tableHTML = '';
  const processedLines: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.startsWith('|') && line.endsWith('|')) {
      if (line.includes('---')) continue; // skip table formatting row
      const cells = line
        .slice(1, -1)
        .split('|')
        .map((c) => c.trim());
      if (!inTable) {
        inTable = true;
        tableHTML = `<table style="width:100%; border-collapse:collapse; margin:16px 0; font-size:11px;"><thead><tr style="background:#f1f5f9;">`;
        cells.forEach((c) => {
          tableHTML += `<th style="border:1px solid #cbd5e1; padding:6px 8px; text-align:left; font-weight:700;">${formatInline(c)}</th>`;
        });
        tableHTML += `</tr></thead><tbody>`;
      } else {
        tableHTML += `<tr>`;
        cells.forEach((c) => {
          tableHTML += `<td style="border:1px solid #e2e8f0; padding:6px 8px;">${formatInline(c)}</td>`;
        });
        tableHTML += `</tr>`;
      }
    } else {
      if (inTable) {
        inTable = false;
        tableHTML += `</tbody></table>`;
        processedLines.push(tableHTML);
        tableHTML = '';
      }
      processedLines.push(line);
    }
  }
  if (inTable) {
    tableHTML += `</tbody></table>`;
    processedLines.push(tableHTML);
  }

  return processedLines
    .map((line) => {
      if (line.startsWith('<table')) return line;
      if (line.startsWith('### ')) {
        return `<h3 style="font-size:14px; font-weight:700; color:#0f172a; margin-top:16px; margin-bottom:8px; border-bottom:1px solid #e2e8f0; padding-bottom:4px;">${formatInline(line.slice(4))}</h3>`;
      }
      if (line.startsWith('## ')) {
        return `<h2 style="font-size:16px; font-weight:700; color:#0f172a; margin-top:20px; margin-bottom:10px;">${formatInline(line.slice(3))}</h2>`;
      }
      if (line.startsWith('# ')) {
        return `<h1 style="font-size:19px; font-weight:800; color:#0f172a; margin-top:22px; margin-bottom:12px;">${formatInline(line.slice(2))}</h1>`;
      }
      if (line.startsWith('- ') || line.startsWith('* ')) {
        return `<div style="margin-left:12px; margin-bottom:4px;">• ${formatInline(line.slice(2))}</div>`;
      }
      if (line.startsWith('---')) {
        return `<hr style="border:none; border-top:1px solid #e2e8f0; margin:16px 0;" />`;
      }
      if (!line.trim()) return '<div style="height:6px;"></div>';
      return `<p style="margin-bottom:6px; line-height:1.5;">${formatInline(line)}</p>`;
    })
    .join('');
}

export async function exportToPDF(markdownContent: string, filename = 'Research_Lead_Report.pdf'): Promise<void> {
  const container = document.createElement('div');
  container.className = 'pdf-export-container';
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.top = '0';
  container.style.width = '800px';
  container.style.padding = '32px';
  container.style.backgroundColor = '#ffffff';
  container.style.color = '#0f172a';
  container.style.fontFamily = 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';

  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  container.innerHTML = `
    <div style="border-bottom: 2px solid #3b82f6; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end;">
      <div>
        <h1 style="font-size: 22px; font-weight: 800; color: #1e293b; margin: 0; letter-spacing: -0.5px;">AI Research & Lead Generation Report</h1>
        <p style="font-size: 12px; color: #64748b; margin: 4px 0 0 0;">Generated by Intelligent Scraping & Lead Scoring Engine</p>
      </div>
      <span style="font-size: 11px; font-weight: 600; color: #3b82f6; background: #eff6ff; padding: 4px 8px; border-radius: 6px;">${dateStr}</span>
    </div>
    <div class="pdf-markdown-body" style="font-size: 12px; line-height: 1.5; color: #334155;">
      ${parseMarkdownToSimpleHTML(markdownContent)}
    </div>
  `;

  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const imgWidth = 210; // A4 width mm
    const pageHeight = 297; // A4 height mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    pdf.save(filename);
  } finally {
    if (container.parentNode) {
      container.parentNode.removeChild(container);
    }
  }
}
